### PR TITLE
feat: slow down the logo cog 2x

### LINKED ISSUE #44: Stop animated cog
Request from a user:
Could the animated cog on the website be replaced with a static version, as it’s really distracting when trying to read pages (you could use the [prefers-reduced-motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) CSS media query but I don’t know how many people who could benefit will be aware of how to change that setting so it might be simpler to remove the animation entirely).

### PR DESCRIPTION
**Pull request by ctwhome**
Fixes #44 
Before and after:

### CODE REVIEW

**Comment by ctwhome** [comment]
once the dropdown menus is merge to main the build will be fixed

**Comment by c-martinez** [comment]
Tried to re-deploy, but it seems to still break. Any ideas why?

**Comment by ctwhome** [comment]
now yes!

**Review by c-martinez — APPROVED** [review]
Great!

**Comment by ctwhome** [comment]
you can test the new accessibility behaviour from the updated pull request: https://deploy-preview-51--wosss.netlify.app/

**Review by c-martinez — APPROVED** [review]
Great! this fixes #44

**Pull request merged**
